feat(acessibility): added aria properties to resolve accessibility is…
vtex-apps/drawer pull request #73
Opened 2023-10-09 14:26 UTC by joaocongio

#### What problem is this solving?

Drawer ajuste apontado pelo Lighthouse: "Os elementos [aria-hidden="true"] contêm descendentes focalizáveis"
Alterado a lógica para valor do atributo aria-hidden, pois quando o minicart não está aberto, o botão deve ter o atributo aria-hidden="false" e não "true". E quando o minicart estiver aberto, esses valores devem se inverter, ou seja, o botão receber o atributo aria-hidden="true", já que agora o minicart é exibido e o botão não.

DrawerCloseButton foi adicionado aria-label e id para facilitar a identificação aos leitores de tela.

Swipable foi removido o atributo aria-hidden, pois também estava impactando na acessibilidade apontada pelo LightHouse: "Os elementos [aria-hidden="true"] contêm descendentes focalizáveis".

#### How to test it?

[Workspace](https://www.samsclub.com.br/?workspace=testeacessibilidade)

Executar o teste no Lighthouse ou PageSpeed.

#### Screenshots or example usage:

Antes da alteração:
![minicart before](https://github.com/vtex-apps/drawer/assets/22462037/392c1fe5-1628-47d2-b8b8-45545da0039e)

Depois da alteração (o ajuste não foi mais apontado pelo Lighthouse):
![Minicart After](https://github.com/vtex-apps/drawer/assets/22462037/d6075511-9f88-4242-a064-4d52bec3780f)

Antes da alteração:
![Swipable Antes](https://github.com/vtex-apps/drawer/assets/22462037/d6d7f6aa-20c0-4f1d-b7d7-72e7d6c57fc0)

Depois da alteração (o ajuste não foi mais apontado pelo Lighthouse):
![Swipable Depois](https://github.com/vtex-apps/drawer/assets/22462037/d293b4e4-85fa-4b90-a26e-0ce83f05dd39)

2023-10-09 14:27 UTC, joaocongio commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2023-11-06 18:49 UTC, filipewl requested changes
Opa João! Obrigado por mais essa contribuição.

Por favor, dá uma olhada nos meus comentários. Acredito que pra poder fazer o merge nós precisaremos:

1. Internacionalizar a label do botão de fechar pra não deixar só em inglês.
2. Rever a remoção do `aria-hidden` que comentei no `Swipable`. Eu tenho a impressão que fazer a checagem do `props.enabled` antes de renderizar o `props.children` pode resolver já que quando `aria-hidden="false"`, não seria mais renderizado o botão de fechar que está focusable.

Me diz aí o que você acha!

2023-11-06 18:49 UTC, filipewl commented on react/DrawerCloseButton.tsx
> +      id="closeIcon"
Acredito que o `id` aqui não seja necessário pra resolver o problema original, então sugeriria não adicioná-lo agora. O que achas?
```suggestion
```

2023-11-06 18:49 UTC, filipewl commented on react/DrawerCloseButton.tsx
> +      aria-label="Close Icon Button"
Para evitar de termos hardcoded essa label em inglês, você conseguiria aplicar [essa sugestão](https://github.com/vtex-apps/store-components/pull/1096#discussion_r1378269632) de internacionalização? 

Acho que seguiria o mesmo princípio!

2023-11-06 18:49 UTC, filipewl commented on react/Swipable.tsx
> -        aria-hidden={this.props.enabled ? 'false' : 'true'}
Eu acredito que aqui este atributo está correto. Quando o componente não está visível, temos `aria-hidden="true"` (1). E quando está visível temos `aria-hidden="false"` (2).

(1)|(2)
-|-
![CleanShot 2023-11-06 at 15 12 24](https://github.com/vtex-apps/drawer/assets/381395/92186651-b2fd-4972-a398-23fe6de27683)|![CleanShot 2023-11-06 at 15 11 43](https://github.com/vtex-apps/drawer/assets/381395/6438cc04-5b11-4653-b358-f13b0b74c8e9)

O problema apontado pelo LH é que quando ele não está visível (1), dentro dele existe algum outro elemento que é _focusable_. Esse elemento é `button` com o ícone de fechar o drawer:
![CleanShot 2023-11-06 at 15 23 53](https://github.com/vtex-apps/drawer/assets/381395/613f6de1-61d4-49c9-acf1-b16f73b44477)

Uma maneira que pensei de resolver isso neste componente é só renderizar os `children` se a prop `enabled` for verdadeira. Você conseguiria testar esse caso?

2023-11-06 18:49 UTC, filipewl commented on react/Drawer.tsx
> +        aria-hidden={!isMenuOpen ? 'false' : 'true'}
Boa! Isso corrige de fato esse valor.

Antes|Depois
-|-
![CleanShot 2023-11-06 at 15 39 00](https://github.com/vtex-apps/drawer/assets/381395/3d675270-3ba8-445c-8620-964010d7b3fd)|![CleanShot 2023-11-06 at 15 39 35](https://github.com/vtex-apps/drawer/assets/381395/35cd1d46-2d26-4e9a-b131-45d197968db9)

2023-11-08 17:20 UTC, joaocongio commented on react/DrawerCloseButton.tsx
> +      aria-label="Close Icon Button"
Alterado!

2023-11-08 17:24 UTC, joaocongio commented on react/Swipable.tsx
> -        aria-hidden={this.props.enabled ? 'false' : 'true'}
Sim, fez sentido.
Renderizando o children apenas quando a propriedade this.props.enabled for true, evita de renderizar o botão que é focusable=true.
Dessa forma, voltei o aria-hidden à div pai.

2024-01-04 16:46 UTC, gvc commented on react/DrawerCloseButton.tsx
> +      id="closeIcon"
@joaocongio podes seguir com a remoção do id? Já que estamos colocando de forma incondicional os aria-label, acredito que deixar sem o id é melhor até por que os usuários não terão controle sobre o id e pode conflitar com outro elemento na página.

2024-01-08 18:36 UTC, joaocongio commented on react/DrawerCloseButton.tsx
> +      id="closeIcon"
@gvc propriedade id removida. Pode verificar novamente, por favor?

2024-01-08 21:01 UTC, gvc approved these changes

2024-01-09 18:17 UTC, merged