feat: add skeleton to drawer component
vtex-apps/drawer pull request #81
Opened 2024-11-06 08:45 UTC by EnriqueePerez

#### What problem is this solving?

When the drawer contains too many components the INP performance time is too high. With this change, a basic skeleton is shown while all the childrens are being mounted.

#### How to test it?

[Workspace](https://enriquedev--dunnesstores.myvtex.com/)

#### Screenshots or example usage:

<img width="428" alt="Screenshot 2024-11-06 at 09 43 15" src="https://github.com/user-attachments/assets/4310cd72-d339-4d24-90d3-06df5ddad75f">

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2024-11-06 14:55 UTC, iago1501 commented on react/Drawer.tsx
> +      setTimeout(() => {
Why is this setTimeout necessary?

2024-11-06 14:59 UTC, beatrizmaselli commented on react/Drawer.tsx
> +      setTimeout(() => {
Since its just to defer maybe you could change to `Promise.resolve().then(() => setShouldRenderChildrenNow(true))`

what do you think @EnriqueePerez ?

2024-11-06 19:46 UTC, iago1501 requested changes

2024-11-06 19:46 UTC, iago1501 commented on react/Drawer.tsx
> +                  (shouldRenderChildrenNow ? children : <></>)}
Maybe instead of a simple div, you could use the same approach that we use in shipping container with a real skeleton: 

https://github.com/vtex-apps/store-components/blob/15c6c2eb1a1f9b6284680d51bda4838fcef73820/react/components/ShippingSimulator/Wrapper.js#L189-L191

https://github.com/vtex-apps/store-components/blob/master/react/components/ShippingSimulator/Loader.js#L6

2024-11-07 09:08 UTC, beatrizmaselli commented on react/Drawer.tsx
> +                  (shouldRenderChildrenNow ? children : <></>)}
@iago1501 there is no gain at user experience applying this skeleton here. I checked some other sides has benchmark and they do not apply any skeleton for those cases so what would be the gain here?
The empty div to open a side menu is a straightforward and performance-friendly choice, considering that the menu opens instantly and the actual content loads quickly.

2024-11-07 13:45 UTC, EnriqueePerez commented on react/Drawer.tsx
> +      setTimeout(() => {
Thanks to the setTimeout, the drawer will be rendered instanly, reducing the INP and the children are going to be mounted once the drawer is first mounted. I tried with promise but seems that the best approach is using this.

2024-11-13 17:39 UTC, closed without merging